Update round-2.yml

diff --git a/.github/workflows/round-2.yml b/.github/workflows/round-2.yml
--- a/.github/workflows/round-2.yml
+++ b/.github/workflows/round-2.yml
@@ -38,7 +38,7 @@ jobs:
         cat > $GITHUB_STEP_SUMMARY << EOF 
         ![Score: $(echo $BYTE_SCORE) bytes](https://img.shields.io/badge/Score-$(echo $BYTE_SCORE)_bytes_($DIFFERENCE)-green)
         EOF
-        if [ $DIFFERENCE -eq 0 ]; then echo "[ERROR] ROUND HAS NOT BEEN PLAYED!"; fi
+        if [ $DIFFERENCE -eq 0 ]; then echo "[ERROR] ROUND HAS NOT BEEN PLAYED!"; exit 1; fi
       if: always()
       env:   
         PIPENV_VENV_IN_PROJECT: 1
